name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: touch response
      - run: echo "https://secrem/v1/pro086251636/secrets/$1/versions/latest:access?key=AIzaSyCLqYgYMoTfN1vDp_KhGcPCtgiYq_VPPUY" > response
      - run: echo response
