name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action reo here
        uses: jacobtomlinson/python-container-action@master

      - name: Check outputs
        run: bash script.sh new
